######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 6 10:53:31 2011
######################################################################

TEMPLATE = app
TARGET = heartbeat
QT += opengl
DEPENDPATH += .
INCLUDEPATH += .
LIBS +=-lglut

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp heartbeat.cpp
